"use strict";
if(typeof Q!=="function"||!Array.isArray(QB)){throw new Error("WNET midterm bank requires the base console first");}
Q("5","Even when payloads are encrypted, a passive observer may still learn…",["Frame timing, traffic volume, identifiers and roaming patterns", "The AES key automatically", "The user's plaintext password from every frame", "Nothing at all"],0,"Encryption protects content, but metadata can still reveal operational patterns.");
Q("5","Why can passive reconnaissance make a later active attack more effective?",["It reveals names, channels, client density and authentication methods", "It automatically disables WPA3", "It changes the PoE class", "It removes all segmentation"],0,"Passive collection can map the target before an attacker chooses a specific impersonation or denial-of-service technique.");
Q("5","Deauthentication abuse is commonly used to…",["Force clients off a legitimate AP for disruption or steering", "Increase encryption key length", "Assign an IP address", "Improve roaming security"],0,"Injected deauthentication can create denial of service or push clients toward attacker-controlled infrastructure.");
Q("5","Why would simply increasing the WEP key length not repair WEP?",["Its structural flaws—short IV, weak per-packet construction, static sharing and weak integrity—remain", "Long keys cannot encrypt data", "WEP never used a cipher", "Only the SSID length matters"],0,"WEP's failure is architectural, not just about nominal key length.");
Q("5","Which statement about the PMK and the four-way handshake is correct?",["The PMK is sent in message 1", "The handshake proves possession of the PMK and derives fresh session keys without sending the PMK", "The PMK is the same as the GTK", "The handshake is only for DHCP"],1,"The four-way handshake uses nonces and MICs to prove both sides share the PMK and to derive/install fresh working keys.");
Q("5","Which key protects unicast traffic for one client–AP pair?",["PTK", "GTK", "SSID", "IV"],0,"The Pairwise Transient Key is specific to the client–AP session. The GTK is for broadcast/multicast.");
Q("5","Why is WPA3-Enterprise more than simply 'a newer cipher'?",["It combines managed identity/key establishment and protected management posture with enterprise credential governance", "It removes all authentication", "It is a new Ethernet cable type", "It uses WEP internally"],0,"The course frames WPA3-Enterprise as a broader managed security posture, not just a cipher swap.");
Q("5","What operational mistake can make PEAP vulnerable to an evil twin?",["Disabling server-certificate validation / accepting any certificate", "Using a strong server certificate", "Segmenting guest traffic", "Using RADIUS"],0,"If clients do not validate the server certificate, a fake AP/authentication server can build a tunnel and harvest inner credentials.");
Q("5","What is the key design tension in segmentation?",["Too coarse leaves systems exposed; too granular becomes brittle to administer", "More segments always reduce all operational complexity", "Segmentation replaces authentication", "Segmentation increases the threat source"],0,"Segmentation should reduce blast radius without creating an unmanageable policy structure.");
