"use strict";
(function(){
if(window.__wnMidtermLoaded)return;window.__wnMidtermLoaded=true;
var TS=["1","2","3","4","5"],counts={};TS.forEach(function(t){counts[t]=QB.filter(function(q){return q.t===t}).length});
var drills=document.getElementById("drills"),wrap=drills&&drills.querySelector(".wrap");if(!wrap)return;
var lede=wrap.querySelector(".lede");if(lede)lede.innerHTML='Midterm prep for the announced <b>50-question multiple-choice exam</b>, plus flashcards and quick drills.';
var qBank=document.getElementById("qBank"),sQs=document.getElementById("sQs");if(qBank)qBank.textContent=QB.length;if(sQs)sQs.textContent=QB.length;
var css=document.createElement("style");css.textContent='.mt{border-color:color-mix(in srgb,var(--gr) 55%,var(--line));background:linear-gradient(135deg,color-mix(in srgb,var(--gr) 8%,var(--panel)),var(--panel))}.mt::before{background:var(--gr)}.mtk{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px;margin:14px 0}.mtk div{border:1px solid var(--line);border-radius:9px;background:var(--panel2);padding:10px 12px}.mtk b{display:block;font:700 18px var(--mono);color:var(--gr)}.mtk span{font:10px var(--mono);color:var(--faint);text-transform:uppercase}.mtrow{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.mtp{height:7px;background:var(--panel2);border:1px solid var(--line);border-radius:99px;overflow:hidden;margin:12px 0}.mtp i{display:block;height:100%;background:var(--gr)}.mth{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;font:11px var(--mono);color:var(--faint)}.mtq{font-size:17px;font-weight:700;margin:8px 0}.mtn{margin-top:10px;padding:10px 12px;border:1px solid var(--line2);border-radius:8px;background:var(--panel2);font-size:13.5px}.mtn.ok{border-color:var(--gr)}.mtn.no{border-color:var(--rd)}.mtsel{border-color:var(--cy)!important}.mtbd{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:12px}.mtbd div{padding:8px;border:1px solid var(--line);border-radius:8px;text-align:center;font:11px var(--mono);color:var(--dim)}.mtbd b{display:block;font-size:15px;color:var(--ink)}.mtrv{max-height:520px;overflow:auto;margin-top:10px}@media(max-width:620px){.mtbd{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(css);
var p=document.createElement("div");p.className="panel mt";p.id="midtermPrep";p.innerHTML='<div class="ph"><span class="badge gr">MIDTERM</span><h2>50-MCQ Prep</h2><span class="badge gr right">'+QB.length+' QUESTION BANK</span></div><p class="sub2">Balanced across all 5 chapters: <b>30 questions per chapter</b>. A full mock draws <b>10 from each chapter = 50 total</b>.</p><div class="mtk"><div><b>50</b><span>exam questions</span></div><div><b>150</b><span>practice bank</span></div><div><b>30 × 5</b><span>balanced chapters</span></div><div><b id="mtBest">—</b><span>best 50-q score</span></div></div><div class="mtrow"><button class="btn go" id="mtExam">▶ 50-Q EXAM</button><button class="btn on" id="mtAll">PRACTICE ALL 150</button><button class="btn no2" id="mtMissed">RETRY MISSED <span id="mtMissN">0</span></button></div><div class="mtrow" id="mtChips"></div><div id="mtBody"><div class="box wild"><b>Best method</b><b>50-Q EXAM</b> hides correctness until the end. <b>Practice</b> explains every answer immediately. Use chapter buttons to attack weak areas.</div></div>';
var first=wrap.querySelector(".panel");if(first)wrap.insertBefore(p,first);else wrap.appendChild(p);
var bankOK=QB.length===150&&TS.every(function(t){return counts[t]===30});
function id(q){return q.t+'|'+q.q}function miss(){return store.get("midtermMissed",[])}function saveMiss(a){store.set("midtermMissed",a)}function meta(){var b=store.get("midtermBest50",-1);document.getElementById("mtBest").textContent=b<0?'—':b+'/50';document.getElementById("mtMissN").textContent=miss().length}meta();
function mix(a){return shuf(a.slice())}function balanced(){var a=[];TS.forEach(function(t){a=a.concat(mix(QB.filter(function(q){return q.t===t})).slice(0,10))});return mix(a)}
var run=null;
function start(qs,label,exam){run={qs:mix(qs),label:label,exam:exam,i:0,answers:[],score:0,misses:[]};render();p.scrollIntoView({behavior:"smooth",block:"start"})}
function render(){var q=run.qs[run.i],ord=mix([0,1,2,3]),pct=Math.round(run.i/run.qs.length*100),h='<div class="mtp"><i style="width:'+pct+'%"></i></div><div class="mth"><span>'+run.label+' · Q'+(run.i+1)+'/'+run.qs.length+'</span><span>CH'+q.t+' · '+CHNAME[q.t]+'</span></div><div class="mtq">'+q.q+'</div>';ord.forEach(function(o){h+='<button class="qopt" data-mt="'+o+'">'+q.o[o]+'</button>'});h+='<div id="mtAfter"></div>';document.getElementById("mtBody").innerHTML=h;document.querySelectorAll('[data-mt]').forEach(function(x){x.onclick=function(){answer(parseInt(x.dataset.mt,10),x)}})}
function answer(c,el){if(run.answers[run.i]!==undefined)return;var q=run.qs[run.i],ok=c===q.a;run.answers[run.i]=c;if(!run.exam){if(ok)run.score++;else run.misses.push({q:q,c:c})}document.querySelectorAll('[data-mt]').forEach(function(x){x.disabled=true;if(!run.exam){var o=parseInt(x.dataset.mt,10);if(o===q.a)x.classList.add("right");else if(o===c)x.classList.add("wrong")}});if(run.exam)el.classList.add("mtsel");document.getElementById("mtAfter").innerHTML=run.exam?'<div class="mtn">Answer locked. Correctness is hidden until the result.</div>':'<div class="mtn '+(ok?'ok':'no')+'"><b>'+(ok?'✓ Correct':'✗ Correct: '+q.o[q.a])+'</b><br>'+q.w+'</div>';document.getElementById("mtAfter").innerHTML+='<div class="row"><button class="btn go" id="mtNext">'+(run.i===run.qs.length-1?(run.exam?'SUBMIT EXAM':'RESULT'):'NEXT →')+'</button></div>';document.getElementById("mtNext").onclick=function(){run.i++;run.i>=run.qs.length?finish():render()}}
function finish(){if(run.exam){run.score=0;run.misses=[];run.qs.forEach(function(q,i){if(run.answers[i]===q.a)run.score++;else run.misses.push({q:q,c:run.answers[i]})});var best=store.get("midtermBest50",-1);if(run.score>best)store.set("midtermBest50",run.score)}var ms=miss();run.misses.forEach(function(m){var k=id(m.q);if(ms.indexOf(k)<0)ms.push(k)});if(!run.exam)run.qs.forEach(function(q,i){if(run.answers[i]===q.a){var k=id(q),j=ms.indexOf(k);if(j>-1)ms.splice(j,1)}});saveMiss(ms);meta();var per={};TS.forEach(function(t){per[t]={n:0,ok:0}});run.qs.forEach(function(q,i){per[q.t].n++;if(run.answers[i]===q.a)per[q.t].ok++});var h='<div class="mtp"><i style="width:100%"></i></div><p class="meta" style="text-align:left">// RESULT</p><div class="big">'+run.score+' / '+run.qs.length+' <span style="font-size:19px;color:var(--dim)">'+Math.round(run.score/run.qs.length*100)+'%</span></div><div class="mtbd">';TS.forEach(function(t){if(per[t].n)h+='<div>CH'+t+'<b>'+per[t].ok+'/'+per[t].n+'</b>'+CHNAME[t]+'</div>'});h+='</div><div class="row">';if(run.misses.length)h+='<button class="btn no2" id="mtReview">REVIEW '+run.misses.length+' MISSES</button>';h+='<button class="btn go" id="mtAgain">NEW RUN</button></div><div id="mtReviewBox"></div>';document.getElementById("mtBody").innerHTML=h;document.getElementById("mtAgain").onclick=function(){run.exam?start(balanced(),"50-Q EXAM",true):start(run.qs,run.label,false)};var r=document.getElementById("mtReview");if(r)r.onclick=review}
function review(){var h='<div class="mtrv">';run.misses.forEach(function(m,i){h+='<div class="mtn no"><b>'+(i+1)+'. CH'+m.q.t+' · '+m.q.q+'</b><br><span style="color:var(--rd)">Your answer: '+(m.c===undefined?'No answer':m.q.o[m.c])+'</span><br><span style="color:var(--gr)">Correct: '+m.q.o[m.q.a]+'</span><br><span style="color:var(--dim)">'+m.q.w+'</span></div>'});document.getElementById("mtReviewBox").innerHTML=h+'</div>'}
TS.forEach(function(t){var b=document.createElement("button");b.className="chip";b.textContent='CH'+t+' · '+CHNAME[t]+' · '+counts[t];b.onclick=function(){start(QB.filter(function(q){return q.t===t}),'CH'+t+' PRACTICE',false)};document.getElementById("mtChips").appendChild(b)});
document.getElementById("mtExam").onclick=function(){start(balanced(),"50-Q EXAM",true)};document.getElementById("mtAll").onclick=function(){start(QB,"ALL 150 PRACTICE",false)};document.getElementById("mtMissed").onclick=function(){var ids=miss(),qs=QB.filter(function(q){return ids.indexOf(id(q))>-1});if(qs.length)start(qs,"MISSED-QUESTION RETRY",false);else document.getElementById("mtBody").innerHTML='<div class="mtn ok"><b>No saved misses.</b> Complete a practice set or exam first.</div>'};
if(!bankOK)document.getElementById("mtBody").insertAdjacentHTML("afterbegin",'<div class="mtn no"><b>Bank warning:</b> expected 150 questions / 30 per chapter. Current: '+JSON.stringify(counts)+'</div>');
})();
